CRM_PFA-Web/src/main/java/com/insat/gl5/crm_pfa/web/controller/NotificationController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.insat.gl5.crm_pfa.web.controller;

import com.insat.gl5.crm_pfa.model.BackendUser;
import com.insat.gl5.crm_pfa.model.Contact;
import com.insat.gl5.crm_pfa.model.Notification;
import com.insat.gl5.crm_pfa.service.NotificationService;
import com.insat.gl5.crm_pfa.service.qualifier.CurrentContact;
import com.insat.gl5.crm_pfa.service.qualifier.CurrentUser;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 * 
 * @author Mu7ammed 3li -- mohamed.ali.affes@gmail.com --
 */
@Named
@SessionScoped
public class NotificationController implements Serializable {

    @Inject
    private NotificationService notificationService;
    @Inject
    @CurrentContact
    private Contact currentContact;
    @Inject
    @CurrentUser
    private BackendUser currentUser;
    private Long id;

    /**
     * @return the notificationsNumber
     */
    public String consult(Notification notification) {
        String link = notification.getLink();
        setId((Long) Long.parseLong(link.substring(link.indexOf("=") + 1, link.length())));
        link = link.substring(0, link.indexOf("?"));
        notification.setReaded(true);
        return link;
    }

    /**
     * @return the notificationsNumber
     */
    public int getContactNotificationsNumber() {
        return notificationService.getUnreadedNotificationsByContact(currentContact).size();
    }

    /**
     * @return the notifications
     */
    public List<Notification> getContactNotifications() {
        return notificationService.getAllNotificationsByContact(currentContact);
    }

    /**
     * @return the notificationsNumber
     */
    public int getBackendUserNotificationsNumber() {
        return notificationService.getUnreadedNotificationsByBackendUser(currentUser).size();
    }

    /**
     * @return the notifications
     */
    public List<Notification> getBackendUserNotifications() {
        return notificationService.getAllNotificationsByBackendUser(currentUser);
    }

    /**
     * @return the id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Long id) {
        this.id = id;
    }
}

CRM_PFA-Web/src/main/webapp/WEB-INF/template/activationMwsTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet library="css" name="default.css" />
        <h:outputStylesheet library="css" name="cssLayout.css" />
        <ui:insert name="cssAndJs"></ui:insert>
        <title><ui:insert name="title">CRM-PFA Administration</ui:insert></title>
        <!-- Required Stylesheets -->
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/reset.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/text.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/fluid.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/fonts/ptsans/stylesheet.css" media="screen" />

        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/mws.style.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/icons/icons.css" media="screen" />


        <!-- Theme Stylesheet -->
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/mws.theme.css" media="screen" />

        <!--for accordeon panel-->
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/jui/jquery.ui.css" media="screen" />
        <!-- JavaScript Plugins -->

        <!--ya3ml machakel-->
<!--        <script type="text/javascript" src="#{request.contextPath}/resources/mws/js/demo.js"></script>-->

        <!-- For showing notif and msg list -->
        <script type="text/javascript" src="#{request.contextPath}/resources/mws/js/mws.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $("div#mws-login .mws-login-back").mouseover(function(event) {
                    $(this).find("a").animate({'left':0})
                }).mouseout(function(event) {
                    $(this).find("a").animate({'left':70})
                });
            });
        </script>
    </h:head>

    <h:body >


        <div id="mws-login" style="width: 500px;height: 300px">
            <h1>Activation du compte</h1>
            <br/>
            <br/>
            <div id="mws-login-form">
                <ui:insert name="register">
                </ui:insert>
            </div>
            <p:messages id="messages" globalOnly="true" />
        </div>
    </h:body>
</html>

CRM_PFA-Web/src/main/webapp/WEB-INF/template/clientTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet library="css" name="default.css" />
        <h:outputStylesheet library="css" name="cssLayout.css" />
        <ui:insert name="cssAndJs"></ui:insert>
        <title><ui:insert name="title">CRM-PFA</ui:insert></title>
        <!-- Required Stylesheets -->
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/reset.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/text.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/fluid.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/fonts/ptsans/stylesheet.css" media="screen" />

        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/mws.style.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/icons/icons.css" media="screen" />


        <!-- Theme Stylesheet -->
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/mws.theme.css" media="screen" />

        <!-- JavaScript Plugins -->
<!--        <script type="text/javascript" src="#{request.contextPath}/resources/mws/js/jquery-1.7.1.min.js"></script>-->



        <!-- For showing notif and msg list -->
        <script type="text/javascript" src="#{request.contextPath}/resources/mws/js/mws.js"></script>
    </h:head>

    <h:body>
        <div id="mws-header" class="clearfix">
            <div id="mws-logo-container">
                <div id="mws-logo-wrap">
                    <img src="#{request.contextPath}/resources/images/crm-pfa.png" alt="mws admin" />
                </div>
            </div>

            <div id="mws-user-tools" class="clearfix">
                <div id="mws-user-notif" class="mws-dropdown-menu">
                    <a href="#" class="mws-i-24 i-alert-2 mws-dropdown-trigger">Notifications</a>
                    <span class="mws-dropdown-notif">#{notificationController.contactNotificationsNumber}</span>
                    <div class="mws-dropdown-box">
                        <div class="mws-dropdown-content">
                            <h:form>
                                <ul class="mws-messages">
                                    <ui:repeat value="#{notificationController.contactNotifications}"
                                               var="notif">
                                        <li class="#{not notif.readed ? 'unread' : 'read'}">
                                            <h:commandLink  action="#{notificationController.consult(notif)}" >
                                                <span class="message">
                                                    #{notif.content}
                                                </span>
                                                <span class="time">
                                                    <h:outputText value="#{notif.createdOn}">
                                                        <f:converter converterId="dateTimeConverter"/>
                                                    </h:outputText>
                                                </span>
                                            </h:commandLink>
                                        </li>
                                    </ui:repeat>
                                </ul>
                            </h:form>
                            <div class="mws-dropdown-viewall">
                                <h:form>
                                    <h:commandLink value="Afficher toutes" action="/frontoffice/notifications/list" />
                                </h:form>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="mws-user-info" class="mws-inset">
                    <div id="mws-user-photo">
                        <p:graphicImage value="/CRMData/contacts/#{currentContact.imageURL}"  alt="User Photo"/>  
                    </div>
                    <div id="mws-user-functions">
                        <div id="mws-username">
                            <h:outputText value="Bienvenue" style="color: white"/>
                            <h:outputText value=" #{currentContact.firstName} #{currentContact.lastName}"/>
                        </div>
                        <h:form>
                            <ul>
                                <li><h:commandLink value="Profile" action="/frontoffice/myProfile"/></li>
                                <li><h:commandLink value="Changer mot de passe" action="/frontoffice/users/changePassword?faces-redirect=true"/></li>
                                <li><h:commandLink value="Logout" action="/login" actionListener="#{identity.logout()}"/></li>
                            </ul>
                        </h:form>
                    </div>
                </div>
            </div>

        </div>

        <div id="mws-wrapper">
            <div id="mws-sidebar-stitch"></div>
            <div id="mws-sidebar-bg"></div>
            <div id="mws-sidebar">

                <div id="mws-navigation">
                    <h:form>
                        <ul>
                            <li>
                                <h:commandLink action="/frontoffice/home" value="Tableau de bord"  class="mws-i-24 i-home"/>
                            </li>
                            <li>
                                <h:commandLink action="/frontoffice/ticket/list" value="Mes tickets" class="mws-i-24 i-text-documents"/>
                            </li>
                            <li>
                                <h:commandLink action="/frontoffice/agenda/calendar" value="Calendrier" class="mws-i-24 i-day-calendar"/>
                            </li>
                        </ul>
                    </h:form>
                </div>
            </div>
            <div id="mws-container" class="clearfix">
                <div class="container">
                    <div class="mws-report-container clearfix">
                        <ui:insert name="body">Content</ui:insert>
                    </div>
                    <div id="mws-footer">
                        <ui:insert name="bottom">Copyright CRM-PFA 2012. Tous droits réservés.</ui:insert>
                    </div>
                </div>
            </div>
        </div>
    </h:body>

</html>

CRM_PFA-Web/src/main/webapp/WEB-INF/template/generalTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet library="css" name="default.css" />
        <h:outputStylesheet library="css" name="cssLayout.css" />
        <ui:insert name="scripts"></ui:insert>
        <title><ui:insert name="title">Default Title</ui:insert></title>
    </h:head>

    <h:body>
        <p:layout fullPage="true">
            <p:layoutUnit position="north" style="border: none;">
                <h:form> 
                    <p:dock position="top">
                        <p:menuitem value="Accueil" icon="/resources/images/menu/Accueil.png" action="/home" ajax="false"/>
                        <p:menuitem value="Tiers" icon="/resources/images/menu/Tiers.png" action="/backoffice/accounts/list" ajax="false"/>
                        <p:menuitem value="Commercial" icon="/resources/images/menu/Commercial.png" action="/backoffice/agenda/calendar" ajax="false"/>
                        <p:menuitem value="Produits Services" icon="/resources/images/menu/Produits.png" action="/data/accueil/accueilProduit" ajax="false"/>
                        <p:menuitem value="Financier" icon="/resources/images/menu/Financier.png" action="/data/accueil/accueilFinancier" ajax="false"/>
                        <p:menuitem value="Production" icon="/resources/images/menu/production.png" onclick="dlg3.show();"/>
                        <p:menuitem value="Projet" icon="/resources/images/menu/projet.png" onclick="dlg3.show();"/>
                        <p:menuitem value="Configuration" icon="/resources/images/menu/Configuration.png" action="/data/accueil/accueilConfiguration" ajax="false"/>
                        <p:menuitem value="A propos" icon="/resources/images/menu/A_propos.png" onclick="dlg3.show();"/>
                    </p:dock>
                </h:form>
                <p:spacer height="50"/>
                <h1 align="left" style="border: none;">
                    <ui:insert name="titre_principal">Titre principal</ui:insert>
                </h1>
            </p:layoutUnit>
            <p:layoutUnit position="west" size="200" style="border: none;">
                
                <p:accordionPanel activeIndex="-1">
                    <ui:insert name="menu">
                        <p:tab title="A compléter">
                            Données du template
                        </p:tab>
                    </ui:insert>
                </p:accordionPanel>  
                <ui:insert name="switch">
                    
                </ui:insert>
            </p:layoutUnit>
            <p:layoutUnit position="center" style="border: none; ">
                <p:dialog header="Information..." width="400" height="250" widgetVar="dlg3" showEffect="explode" hideEffect="bounce" >
                    <center>
                        <h:graphicImage value="/resources/images/menu/production.png" />
                        <h:graphicImage value="/resources/images/menu/projet.png" />
                        <br/>
                        <h:outputText value="Ce domaine fonctionnel n'est pas encore implémenté..." />
                        <br/>
                        <h:outputText value="L'implémentation est prévue pour 2012." />
                        <br/>
                        <h:outputText value="Merci." />
                        <br/>
                        <br/>
                        <h:outputText value="ADMINISTRATION" />
                    </center>
                </p:dialog>
<!--                <h3>
                    <ui:insert name="title2">Titre secondaire</ui:insert>
                </h3>
                <p:separator />-->
<!--                <p>-->
                    <ui:insert name="body">Corps de la vue</ui:insert>
<!--                </p>-->
            </p:layoutUnit>
        </p:layout>

    </h:body>

</html>

CRM_PFA-Web/src/main/webapp/WEB-INF/template/generalTemplate2.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet library="css" name="default.css" />
        <h:outputStylesheet library="css" name="cssLayout.css" />
        <ui:insert name="cssAndJs"></ui:insert>
        <title><ui:insert name="title">CRM-PFA Administration</ui:insert></title>
        <!-- Required Stylesheets -->
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/reset.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/text.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/fluid.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/fonts/ptsans/stylesheet.css" media="screen" />

        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/mws.style.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/icons/icons.css" media="screen" />


        <!-- Theme Stylesheet -->
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/mws.theme.css" media="screen" />

        <!--for accordeon panel-->
<!--        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/jui/jquery.ui.css" media="screen" />-->
        <!-- JavaScript Plugins -->

        <!--ya3ml machakel-->
<!--        <script type="text/javascript" src="#{request.contextPath}/resources/mws/js/demo.js"></script>-->

        <!-- For showing notif and msg list -->
        <script type="text/javascript" src="#{request.contextPath}/resources/mws/js/mws.js"></script>
    </h:head>

    <h:body>
        <div id="mws-header" class="clearfix">
            <div id="mws-logo-container">
                <div id="mws-logo-wrap">
                    <img src="#{request.contextPath}/resources/images/crm-pfa-admin.png" alt="mws admin" />
                </div>
            </div>

            <div id="mws-user-tools" class="clearfix">
                <div id="mws-user-notif" class="mws-dropdown-menu">
                    <a href="#" class="mws-i-24 i-alert-2 mws-dropdown-trigger">Notifications</a>
                    <span class="mws-dropdown-notif">#{notificationController.backendUserNotificationsNumber}</span>
                    <div class="mws-dropdown-box">
                        <div class="mws-dropdown-content">
                            <h:form>
                                <ul class="mws-messages">
                                    <ui:repeat value="#{notificationController.backendUserNotifications}"
                                               var="notif">
                                        <li class="#{not notif.readed ? 'unread' : 'read'}">
                                            <h:commandLink  action="#{notificationController.consult(notif)}" >
                                                <span class="message">
                                                    #{notif.content}
                                                </span>
                                                <span class="time">
                                                    <h:outputText value="#{notif.createdOn}">
                                                        <f:converter converterId="dateTimeConverter"/>
                                                    </h:outputText>
                                                </span>
                                            </h:commandLink>
                                        </li>
                                    </ui:repeat>
                                </ul>
                            </h:form>
                            <div class="mws-dropdown-viewall">
                                <h:form>
                                    <h:commandLink value="Afficher toutes" action="/backoffice/notifications/list" />
                                </h:form>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="mws-user-info" class="mws-inset">
                    <div id="mws-user-photo">
                        <img src="#{request.contextPath}/resources/mws/example/profile.jpg" alt="User Photo" />
                    </div>
                    <div id="mws-user-functions">
                        <div id="mws-username">
                            <h:outputText value="Bienvenue" style="color: white"/>
                            <h:outputText value=" #{currentUser.fullName}"/>
                        </div>
                        <h:form>
                            <ul>
                                <li><h:commandLink value="Profile" action="/backoffice/users/myProfile"/></li>
                                <li><h:commandLink value="Changer mot de passe" action="/backoffice/users/changePassword?faces-redirect=true"/></li>
                                <li><h:commandLink value="Logout" action="/login" actionListener="#{identity.logout()}"/></li>
                            </ul>
                        </h:form>
                    </div>
                </div>
            </div>

        </div>

        <div id="mws-wrapper">
            <div id="mws-sidebar-stitch"></div>
            <div id="mws-sidebar-bg"></div>
            <div id="mws-sidebar">

                <div id="mws-navigation">
                    <h:form>
                        <ul>
                            <li><h:commandLink action="/backoffice/home" value="Acceuil" styleClass="mws-i-24 i-home" /></li>
                            <li>
                                <a href="#" class="mws-i-24 i-users"><h:outputText  value="Gestion des comptes"/></a>
                                <ul>
                                    <li><h:commandLink action="/backoffice/accounts/list" value="Sociétés"  /></li>
                                    <li><h:commandLink action="/backoffice/contacts/list" value="Contacts" /></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#" class="mws-i-24 i-scan-label"><h:outputText  value="Gestion des produits"/></a>
                                <ul>
                                    <li><h:commandLink action="/backoffice/products/list" value="Produits" /></li>
                                    <li><h:commandLink action="/backoffice/products/category/list" value="Catégories" /></li>
                                    <li><h:commandLink action="/backoffice/products/tva/list" value="TVA" /></li>
                                </ul>
                            </li>
                            <li>
                                <h:commandLink class="mws-i-24 i-facebook-like" action="/backoffice/opportunities/list" value="Gestion des opportunités" />
                            </li>
                            <li>
                                <h:commandLink action="/backoffice/ticket/list" value="Tickets" class="mws-i-24 i-tag"/>
                            </li>
                            <li>
                                <h:commandLink action="/backoffice/agenda/calendar" value="Calendrier" class="mws-i-24 i-day-calendar"/>
                            </li>
                            <li>
                                <a href="#" class="mws-i-24 i-unlocked"><h:outputText  value="Gestion d'accès"/></a>
                                <ul>
                                    <li><h:commandLink value="Créer utilisateur" action="/backoffice/users/createUser"
                                                       actionListener="#{userManagement.beginConversation()}" /></li>
                                    <li><h:commandLink action="/backoffice/users/listGroups" value="Gestion des groupes" /></li>
                                    <li><h:commandLink action="/backoffice/users/listRoleTypes" value="Gestion des rôles" /></li>

                                </ul>
                            </li>
                        </ul>
                    </h:form>
                </div>
            </div>
            <div id="mws-container" class="clearfix">
                <div class="container">
                    <div class="mws-report-container clearfix">
                        <ui:insert name="body">Content</ui:insert>
                    </div>
                    <div id="mws-footer">
                        <ui:insert name="bottom">Copyright CRM-PFA 2012. Tous droits réservés.</ui:insert>
                    </div>
                </div>
            </div>
        </div>



    </h:body>

</html>

CRM_PFA-Web/src/main/webapp/WEB-INF/template/loginMwsTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet library="css" name="default.css" />
        <h:outputStylesheet library="css" name="cssLayout.css" />
        <ui:insert name="cssAndJs"></ui:insert>
        <title><ui:insert name="title">CRM-PFA Administration</ui:insert></title>
        <!-- Required Stylesheets -->
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/reset.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/text.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/fluid.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/fonts/ptsans/stylesheet.css" media="screen" />

        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/mws.style.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/icons/icons.css" media="screen" />


        <!-- Theme Stylesheet -->
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/mws.theme.css" media="screen" />

        <!--for accordeon panel-->
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/mws/css/jui/jquery.ui.css" media="screen" />
        <!-- JavaScript Plugins -->

        <!--ya3ml machakel-->
<!--        <script type="text/javascript" src="#{request.contextPath}/resources/mws/js/demo.js"></script>-->

        <!-- For showing notif and msg list -->
        <script type="text/javascript" src="#{request.contextPath}/resources/mws/js/mws.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $("div#mws-login .mws-login-back").mouseover(function(event) {
                    $(this).find("a").animate({'left':0})
                }).mouseout(function(event) {
                    $(this).find("a").animate({'left':70})
                });
            });
        </script>
    </h:head>

    <h:body >


        <div id="mws-login">
            <h1>Connexion</h1>
            <div class="mws-login-lock">
                <img src="#{request.contextPath}/resources/mws/css/icons/24/locked-2.png" alt="" /></div>
            <div id="mws-login-form">
                <h:form id="loginForm" styleClass="mws-form" rendered="#{not identity.loggedIn}">
                    <div class="mws-form-row">
                        <div class="mws-form-item large">
                            <ui:insert name="body"></ui:insert>
                        </div>
                    </div>
                </h:form>
                <h:form id="alreadyLoggedInForm" styleClass="mws-form" rendered="#{identity.loggedIn}">
                    <div class="mws-form-item large">
                        <ui:insert name="loggedIn"></ui:insert>
                        <p:spacer/>
                    </div>
                </h:form>
            </div>
                <ui:insert name="register">
                   
                </ui:insert>
            <p:messages id="messages" globalOnly="true" />
        </div>
    </h:body>
</html>

CRM_PFA-Web/src/main/webapp/WEB-INF/template/loginTemplate.xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>CRM-PFA Administration</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <h:outputStylesheet library="css" name="default.css" />
        <h:outputStylesheet library="css" name="cssLayout.css" />
    </h:head>
    <h:body >
        <div style="padding-top:10px;">
            <h:panelGroup style="width:100%;">
                <ui:insert name="body" id="content"></ui:insert>
            </h:panelGroup>
            <p:spacer height="100%"/>
            <div align="center"  style="vertical-align:bottom; padding-bottom:5px;"><h:graphicImage library="images" value="/presentation/Vente.png" width="35" height="35" style="vertical-align: middle;"/> Copyright © 2012 CRM-PFA.  All rights reserved</div>
        </div>
    </h:body>
</html>