CRM_PFA-Web/src/main/java/com/insat/gl5/crm_pfa/web/controlller/opportunity/ItemsToPurchaseController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.insat.gl5.crm_pfa.web.controlller.opportunity;

import com.insat.gl5.crm_pfa.model.*;
import com.insat.gl5.crm_pfa.service.ItemToPurchaseService;
import com.insat.gl5.crm_pfa.service.ProductService;
import com.insat.gl5.crm_pfa.web.controller.ConversationController;
import java.util.LinkedList;
import java.util.List;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;
import org.jboss.seam.international.status.Messages;

/**
 *
 * @author
 * Mu7ammed
 * 3li
 * --
 * mohamed.ali.affes@gmail.com
 * --
 */
@Named
@ConversationScoped
public class ItemsToPurchaseController extends ConversationController {

    @Inject
    private ItemToPurchaseService itemToPurchaseService;
    @Inject
    private ProductService productService;
    private List<Product> products = new LinkedList<Product>();
    //Liste des produits séléctionnés à partir du datatable
    private List<ItemToPurchase> itemsToPurchase = new LinkedList<ItemToPurchase>();
    private List<ItemToPurchase> lstItemsToDelete = new LinkedList<ItemToPurchase>();
    private List<ItemToPurchase> lstItemsToAdd = new LinkedList<ItemToPurchase>();
    @Inject
    private Messages messages;
    private Product selctedProduct;
    private int quantity;
    private Category filterCategory;
    private String filterProductName;

    public void deleteItem(ItemToPurchase item) throws Exception {
        itemToPurchaseService.deleteItemToPurchase(item);
    }

    public void saveItem(ItemToPurchase item) throws Exception {
        itemToPurchaseService.saveItemToPurchase(item);
    }

    public void initProducts() {
        products = productService.getAllProducts();
    }

    public void loadProducts(List<ItemToPurchase> items) {
        products = productService.getAllProducts();
        itemsToPurchase = items;
    }

    public void addItem() {
        if (quantity > selctedProduct.getQuantity()) {
            messages.error("La quantité est suppérieure au stock !!");
            return;
        }
        ItemToPurchase item = getItemToPurchaseByProduct(selctedProduct);

        if (item == null) {
            itemsToPurchase.add(new ItemToPurchase(quantity, selctedProduct));
        } else {

            if (item.getQuantity() + quantity > selctedProduct.getQuantity()) {
                messages.error("La quantité est suppérieure au stock !!");
                return;
            }
            item.setQuantity(item.getQuantity() + quantity);
        }
        quantity = 0;
//        products.remove(selctedProduct);
    }

    public void removeItem(ItemToPurchase itemToPurchase) {
        itemsToPurchase.remove(itemToPurchase);
//        products.add(itemToPurchase.getProduct());
    }

    private ItemToPurchase getItemToPurchaseByProduct(Product product) {
        for (ItemToPurchase item : itemsToPurchase) {
            if (item.getProduct().equals(product)) {
                return item;
            }
        }
        return null;
    }

    public void populateProducts() {
        products.clear();
        if (filterCategory == null) {
            if (filterProductName == null || filterProductName.isEmpty()) {
                //-------Criteres : none--------//
                products = productService.getAllProducts();
                return;
            }
            //-------Criteres : ProductName--------//
            products = productService.findProductsByLikeName(filterProductName);
            return;
        }
        if (filterProductName == null || filterProductName.isEmpty()) {
            //-------Criteres : Category--------//
            products = productService.findProductsByCategory(filterCategory);
            return;
        }
        //-------Criteres : Category+productName--------//
        products = productService.findProductsByLikeNameAndCategory(filterProductName, filterCategory);
    }

    /**
     * @return
     * the
     * itemsToPurchase
     */
    public List<ItemToPurchase> getItemsToPurchase() {
        return itemsToPurchase;
    }

    /**
     * @param
     * itemsToPurchase
     * the
     * itemsToPurchase
     * to
     * set
     */
    public void setItemsToPurchase(List<ItemToPurchase> itemsToPurchase) {
        this.itemsToPurchase = itemsToPurchase;
    }

    /**
     * @return
     * the
     * selctedProduct
     */
    public Product getSelctedProduct() {
        return selctedProduct;
    }

    /**
     * @param
     * selctedProduct
     * the
     * selctedProduct
     * to
     * set
     */
    public void setSelctedProduct(Product selctedProduct) {
        this.selctedProduct = selctedProduct;
    }

    /**
     * @return
     * the
     * quantity
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * @param
     * quantity
     * the
     * quantity
     * to
     * set
     */
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    /**
     * @return
     * the
     * products
     */
    public List<Product> getProducts() {
        return products;
    }

    /**
     * @param
     * products
     * the
     * products
     * to
     * set
     */
    public void setProducts(List<Product> products) {
        this.products = products;
    }

    /**
     * @return
     * the
     * filterCategory
     */
    public Category getFilterCategory() {
        return filterCategory;
    }

    /**
     * @param
     * filterCategory
     * the
     * filterCategory
     * to
     * set
     */
    public void setFilterCategory(Category filterCategory) {
        this.filterCategory = filterCategory;
    }

    /**
     * @return
     * the
     * filterProductName
     */
    public String getFilterProductName() {
        return filterProductName;
    }

    /**
     * @param
     * filterProductName
     * the
     * filterProductName
     * to
     * set
     */
    public void setFilterProductName(String filterProductName) {
        this.filterProductName = filterProductName;
    }

    /**
     * @return
     * the
     * lstItemsToDelete
     */
    public List<ItemToPurchase> getLstItemsToDelete() {
        return lstItemsToDelete;
    }

    /**
     * @param
     * lstItemsToDelete
     * the
     * lstItemsToDelete
     * to
     * set
     */
    public void setLstItemsToDelete(List<ItemToPurchase> lstItemsToDelete) {
        this.lstItemsToDelete = lstItemsToDelete;
    }

    /**
     * @return
     * the
     * lstItemsToAdd
     */
    public List<ItemToPurchase> getLstItemsToAdd() {
        return lstItemsToAdd;
    }

    /**
     * @param
     * lstItemsToAdd
     * the
     * lstItemsToAdd
     * to
     * set
     */
    public void setLstItemsToAdd(List<ItemToPurchase> lstItemsToAdd) {
        this.lstItemsToAdd = lstItemsToAdd;
    }
}

CRM_PFA-Web/src/main/java/com/insat/gl5/crm_pfa/web/controlller/opportunity/OpportunityController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.insat.gl5.crm_pfa.web.controlller.opportunity;

import com.insat.gl5.crm_pfa.enumeration.DirectionEnum;
import com.insat.gl5.crm_pfa.enumeration.NotificationType;
import com.insat.gl5.crm_pfa.enumeration.OpportunityType;
import com.insat.gl5.crm_pfa.model.*;
import com.insat.gl5.crm_pfa.service.AccountService;
import com.insat.gl5.crm_pfa.service.ContactService;
import com.insat.gl5.crm_pfa.service.NotificationService;
import com.insat.gl5.crm_pfa.service.OpportunityService;
import com.insat.gl5.crm_pfa.service.qualifier.CurrentUser;
import com.insat.gl5.crm_pfa.web.controller.ConversationController;
import com.insat.gl5.crm_pfa.web.exception.ContactRequiredException;
import com.insat.gl5.crm_pfa.web.exception.ProductsRequiredException;
import java.util.LinkedList;
import java.util.List;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;
import org.jboss.seam.international.status.Messages;

/**
 *
 * @author
 * Mu7ammed
 * 3li
 * --
 * mohamed.ali.affes@gmail.com
 * --
 */
@Named
@ConversationScoped
public class OpportunityController extends ConversationController {

    @Inject
    private OpportunityService opportunityService;
    @Inject
    private AccountService accountService;
    @Inject
    private ContactService contactService;
    @Inject
    private NotificationService notificationService;
    @Inject
    private ItemsToPurchaseController itemsToPurchaseController;
    @Inject
    private Opportunity opportunity;
    @Inject
    private Messages messages;
    private String redirect;
    private Account selectedAccount;
    private List<Contact> selectedContacts;
    @Inject
    @CurrentUser
    private BackendUser currentUser;

    /**
     * Save
     * an
     * opportunity
     *
     */
    public String saveOpportunity() {

        try {
            validateContact();
            affectProducts();
            opportunity.setType(OpportunityType.PROPOSITION);
            opportunity.setAssignedTo(currentUser);
            opportunityService.saveOpportunity(getOpportunity());
            notifyContacts();
            messages.info("Opportunité {0} est enregistrée avec succés !", getOpportunity());
            setOpportunity(null);

        } catch (ContactRequiredException e) {
            messages.error("Veuillez choisir le contact");
            return null;
        } catch (ProductsRequiredException e) {
            messages.error("Veuillez choisir les produits");
            return null;
        } catch (Exception e) {
            messages.error("Erreur d'enregistrement de l'Opportunité {0}", getOpportunity());
            return null;
        }
        endConversation();
        return getRedirect();
    }

    /**
     * Edit
     * an
     * Opportunity
     *
     */
    public String editOpportunity() {

        try {
            validateContact();
            editProducts();

            opportunityService.editOpportunity(getOpportunity());
            messages.info("Opportunité {0} est modifiée avec succés !", getOpportunity());

            setOpportunity(null);
        } catch (ContactRequiredException e) {
            messages.error("Veuillez choisir le contact");
            return null;
        } catch (ProductsRequiredException e) {
            messages.error("Veuillez choisir les produits");
            return null;
        } catch (Exception e) {
            messages.error("Erreur de modification de l'Opportunité {0}", getOpportunity());
            return null;
        }
        endConversation();
        return getRedirect();
    }

    private void editProducts() throws ProductsRequiredException {
        if (itemsToPurchaseController.getItemsToPurchase().isEmpty()) {
            throw new ProductsRequiredException();
        }
        for (ItemToPurchase item : itemsToPurchaseController.getLstItemsToDelete()) {
            try {
                itemsToPurchaseController.deleteItem(item);
                opportunity.getItemsToPurchase().remove(item);
            } catch (Exception ex) {
                messages.error("Erreur de supression de l'item {0}", item);
            }
        }
        for (ItemToPurchase item : itemsToPurchaseController.getLstItemsToAdd()) {
            try {
                itemsToPurchaseController.saveItem(item);
                opportunity.getItemsToPurchase().add(item);
            } catch (Exception ex) {
                messages.error("Erreur de l'ajout de l'item {0}", item);
            }
        }
    }

    public void validateContact() throws ContactRequiredException {
        if (opportunity.getRelatedTo() == null) {
            throw new ContactRequiredException();
        }
    }

    public double calculateTotalPrice() {
        double price = 0;
        for (ItemToPurchase item : itemsToPurchaseController.getItemsToPurchase()) {
            price += item.getQuantity() * item.getProduct().getPrice();
        }
        return price;
    }
    public double calculateTotalPrice(Opportunity opp) {
        double price = 0;
        for (ItemToPurchase item : opp.getItemsToPurchase()) {
            price += item.getQuantity() * item.getProduct().getPrice();
        }
        return price;
    }

    public double calculateOpportunityPrice() {
        if (opportunity.getRelatedTo() == null || contactService.getFidelityByContact(opportunity.getRelatedTo()) == null) {
            return calculateTotalPrice();
        }
        return calculateTotalPrice() * ((double)(100 - contactService.getFidelityByContact(opportunity.getRelatedTo()).getScore()) / 100);
    }
    public double calculateOpportunityPrice(Opportunity opp) {
        if (opp.getRelatedTo() == null || contactService.getFidelityByContact(opp.getRelatedTo()) == null) {
            return calculateTotalPrice(opp);
        }
        return calculateTotalPrice(opp) * ((double)(100 - contactService.getFidelityByContact(opp.getRelatedTo()).getScore()) / 100);
    }

    public void initProducts() {
        beginConversation();
        itemsToPurchaseController.initProducts();
    }

    public void loadProducts(Opportunity o) {
        beginConversation();
        opportunity = o;
        selectedAccount = accountService.findById(opportunity.getRelatedTo().getAccount().getId());
        itemsToPurchaseController.loadProducts(opportunity.getItemsToPurchase());
    }

    /**
     * Delete
     * the
     * selected
     * account
     */
    public void deleteOpportunity() {

        try {
            notificationService.deleteNotification(notificationService.getNotificationByOpportunity(opportunity.getId()));
            opportunityService.deleteOpportunity(getOpportunity());
            messages.info("Opportunité {0} est supprimée avec succés !", getOpportunity());
            setOpportunity(null);
        } catch (Exception e) {
            messages.error("Erreur de supression de l'Opportunité {0}", getOpportunity());
        }
        endConversation();
    }

    private void affectProducts() throws ProductsRequiredException {
        if (itemsToPurchaseController.getItemsToPurchase().isEmpty()) {
            throw new ProductsRequiredException();
        }
        opportunity.setItemsToPurchase(itemsToPurchaseController.getItemsToPurchase());
    }

    private void notifyContacts() throws Exception {
        Notification notification = new Notification();
        notification.setContent(currentUser.getFullName()+ " vous invite à consulter l'opportunité ' " + opportunity.getName() + ".");
        notification.setLink("/frontoffice/notifications/viewOpportunity?id=" + opportunity.getId());
        notification.setType(NotificationType.OPPORTUNITE);
        List<NotificationContact> list = new LinkedList<NotificationContact>();
        NotificationContact notificationContact = new NotificationContact(opportunity.getRelatedTo(), currentUser, notification, DirectionEnum.FROM_BACKUSER);
        list.add(notificationContact);
        notification.setNotificationContacts(list);
        notificationService.saveNotificationContact(notificationContact);
        notificationService.saveNotification(notification);
    }

    public List<Contact> getContactsByAccount() {
        if (selectedAccount == null) {
            return null;
        }
        return contactService.getContactsByAccount(accountService.findById(selectedAccount.getId()));
    }

    /**
     * @return
     * the
     * redirect
     */
    public String getRedirect() {
        return redirect;
    }

    /**
     * @param
     * redirect
     * the
     * redirect
     * to
     * set
     */
    public void setRedirect(String redirect) {
        this.redirect = redirect;
    }

    /**
     * @return
     * the
     * opportunity
     */
    public Opportunity getOpportunity() {
        return opportunity;
    }

    /**
     * @param
     * opportunity
     * the
     * opportunity
     * to
     * set
     */
    public void setOpportunity(Opportunity opportunity) {
        this.opportunity = opportunity;
    }

    /**
     * @return
     * the
     * selectedAccount
     */
    public Account getSelectedAccount() {
        return selectedAccount;
    }

    /**
     * @param
     * selectedAccount
     * the
     * selectedAccount
     * to
     * set
     */
    public void setSelectedAccount(Account selectedAccount) {
        this.selectedAccount = selectedAccount;
    }

    /**
     * @return
     * the
     * selectedContacts
     */
    public List<Contact> getSelectedContacts() {
        return selectedContacts;
    }

    /**
     * @param
     * selectedContacts
     * the
     * selectedContacts
     * to
     * set
     */
    public void setSelectedContacts(List<Contact> selectedContacts) {
        this.selectedContacts = selectedContacts;
    }
}

CRM_PFA-Web/src/main/webapp/backoffice/opportunities/form.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:s="http://jboss.org/seam/faces"
                xmlns:p="http://primefaces.org/ui">

    <p:messages id="messages" autoUpdate="true" globalOnly="true"/>   
    <table style="width: 100%">
        <tr>
            <td style="vertical-align: top">
                <h3>Informations générales</h3>
                <p:spacer height="10"/>
                <h:panelGrid columns="2" cellpadding="4">
                    <h:outputLabel value="Nom opportunité :" styleClass="titleLib"/>  
                    <h:panelGrid columns="2">
                        <p:inputText id="newName" value="#{opportunityController.opportunity.name}"
                                     required="true"
                                     requiredMessage="Valeur requise">
                            <p:ajax event="blur"/>
                        </p:inputText>
                        <p:message for="newName"/> 
                    </h:panelGrid>
                    <h:outputLabel value="Type :" styleClass="titleLib"/>  
                    <p:selectOneMenu value="#{opportunityController.opportunity.type}" styleClass="full-width">
                        <f:selectItems value="#{enumValues.opportunityTypes}" var="_c" itemValue="#{_c}" itemLabel="#{_c.displayName}" />  
                    </p:selectOneMenu>
                    <h:outputLabel value="Liée à :" styleClass="titleLib"/> 
                    <h:panelGroup>
                        <h:panelGrid columns="4">

                            <p:selectOneMenu  value="#{opportunityController.selectedAccount}" styleClass="full-width">
                                <f:selectItem  itemValue="#{null}" itemLabel="Selectionnez" />  
                                <f:selectItems value="#{lstAccounts}" var="_a" itemValue="#{_a}" itemLabel="#{_a.name}" />  
                                <p:ajax event="change" update="@this, contactGroup"/>
                            </p:selectOneMenu>
                            <p:spacer/>
                            <h:outputLabel value="Contact :" styleClass="titleLib"/>
                            <h:panelGroup id="contactGroup">
                                <h:outputLabel  value="aucun contact trouvé" style="font-style: italic" rendered="#{opportunityController.contactsByAccount.size() eq 0}"/>
                                <p:selectOneMenu id="contact" value="#{opportunityController.opportunity.relatedTo}" required="true" requiredMessage="Valeur requise" styleClass="full-width" rendered="#{opportunityController.contactsByAccount.size() gt 0}">
                                    <f:selectItems value="#{opportunityController.contactsByAccount}" var="_a" itemValue="#{_a}" itemLabel="#{_a.lastName}" />  
                                    <p:ajax event="change" update="@this"/>
                                </p:selectOneMenu>
                            </h:panelGroup>
                            <p:message for="contact"/>
                        </h:panelGrid>
                    </h:panelGroup>
                    <h:outputLabel value="Date de clôture prévue :" styleClass="titleLib"/>  
                    <h:panelGrid columns="2">
                        <p:calendar id="startDate" pattern="dd/MM/yyyy" value="#{opportunityController.opportunity.closeDate}"  
                                    readOnlyInputText="true"
                                    required="true"
                                    requiredMessage="Valeur requise" >
                        </p:calendar>
                        <p:message for="startDate"/> 
                    </h:panelGrid>
                    <h:outputLabel value="Déscription :" />  
                    <p:inputTextarea rows="5" cols="45" value="#{opportunityController.opportunity.description}"/>
                </h:panelGrid>
            </td>
            <td style="vertical-align: top;">
                <h3>Produits de l'offre</h3>
                <p:spacer height="10"/>
                <table style="width: 100%">
                    <tr>
                        <td colspan="2">
                            <h:panelGrid columns="8" cellspacing="8">
                                <h:outputText value="Catégorie" styleClass="fs12 gras"/>
                                <p:selectOneMenu   value="#{itemsToPurchaseController.filterCategory}"
                                                   styleClass="fs12">
                                    <f:selectItem itemLabel="-- Toutes --" itemValue="#{null}"/> 
                                    <f:selectItems value="#{lstCategories}" var="c" 
                                                   itemLabel="#{c.name}" itemValue="#{c}"/>
                                    <p:ajax event="change" update="@form"/>
                                </p:selectOneMenu>
                                <p:spacer width="10"/>
                                <h:outputText value="Recherche par nom" styleClass="fs12 gras"/>
                                <p:inputText id="nom" value="#{itemsToPurchaseController.filterProductName}" >
                                    <p:ajax event="blur"/>
                                </p:inputText>
                                <p:commandLink title="Filtrer" immediate="true" update="groupProducts"
                                               action="#{itemsToPurchaseController.populateProducts()}">
                                    <h:graphicImage library="images" name="icons/filter.png"/>   
                                </p:commandLink>

                            </h:panelGrid>

                        </td>
                    </tr>
                    <tr>
                        <td valign="top" style="width: 250px">
                            <h:panelGroup id="groupProducts">
                                <p:galleria id="contentGalleria" rendered="#{itemsToPurchaseController.products.size() gt 0}" value="#{itemsToPurchaseController.products}" 
                                            var="product" frameWidth="70" frameHeight="100"  
                                            panelWidth="240" panelHeight="280" transitionInterval="0"  
                                            styleClass="ui-widget-content ui-corner-all">  
                                    <p:graphicImage id="productImage" value="/CRMData/products/#{product.image}" width="120" height="140"/>  
                                    <p:galleriaContent>  
                                        <center>
                                            <h:panelGrid  columns="2" cellpadding="5">  
                                                <f:facet name="header">  
                                                    <p:commandLink  title="Ajouter " oncomplete="cartDialog.show()" >
                                                        <p:graphicImage value="/CRMData/products/#{product.image}"  width="120" height="140"/>  
                                                        <f:setPropertyActionListener target="#{itemsToPurchaseController.selctedProduct}" value="#{product}"/>
                                                    </p:commandLink>
                                                </f:facet>  
                                                <h:outputText value="Référence"/>
                                                <h:outputText value="#{product.reference}"/>
                                                <h:outputText value="Libellé"/>
                                                <h:outputText value="#{product.name}"/>
                                                <h:outputText value="Prix ordinaire"/>
                                                <h:outputText value="#{product.price}"/>
                                            </h:panelGrid>  
                                        </center>
                                    </p:galleriaContent>  
                                </p:galleria>
                                <h:outputLabel value="Pas de produits trouvés" rendered="#{itemsToPurchaseController.products.size() eq 0}"/>
                            </h:panelGroup>
                        </td>
                        <td valign="top" style="width: 380px">
                            <p:panel header="Items séléctionnés" id="cartPanel" >
                                <ui:repeat  value="#{itemsToPurchaseController.itemsToPurchase}" var="item">

                                    <h:panelGrid columns="4" style="width: 100%">
                                        <p:graphicImage value="/CRMData/products/#{item.product.image}"  width="30" height="50"/>   
                                        <h:outputLabel value="#{item.product} "/>
                                        <h:outputLabel value=" Quantité: #{item.quantity}"/>
                                        <p:commandLink  title="Supprimer"  immediate="true" action="#{itemsToPurchaseController.removeItem(item)}" update="@form">
                                            <h:graphicImage library="images" name="constellation/icons/fugue/cross-circle.png" width="16" height="16"/>  
                                        </p:commandLink>
                                    </h:panelGrid>        
                                </ui:repeat>
                            </p:panel>
                            <h:outputText value="Prix d'opportunité : "/>
                            <h:outputText value="#{opportunityController.calculateOpportunityPrice()}"/>
                        </td>
                    </tr>

                </table>    


            </td>
        </tr>  
    </table>

    <p:spacer height="40"/>
</ui:composition>